### ISSUE TITLE
Filter: Einfache Abfrage auf Checkbox funktioniert nur, wenn Aktiv ausgewählt ist

### ISSUE THREAD

**Issue by MacKP** [MetaModels/filter_checkbox#17]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     7.2.14     |                                  |
| Contao version:                     |    4.4.40      |                                  |
| MetaModels version:                 |    Version 2.1.1      |                                  |
| Installation via composer:          | yes |           geht das überhaupt anders???                       |
| Installed MetaModels packages:      |    bundle_all      |                                  |
| DCG version:                        |    2.1.x-dev      |                                  |

## Problem / Konfiguration:

Ich habe eine Checkbox 'Hervorgehoben', und dafür einen Filter eingerichtet ->
Einfache Abfrage:
- Attribut: Hervorgebhoben [checkbox]
- URL-Parameter: -
- Statischer Parameter ist angekreuzt
- Alles andere leer (default)
- Leere Auswahl ermöglichen

## Describe the behaviour of the application

1. Wenn ich jetzt in einer Liste Auswähle, dass alle Items angezeigt werden sollen, die Hervorgehoben sind (= 1) werden mir auch nur die Items angezeigt.
2. Wenn ich den Filter leer lasse, dann werden mir keine Items angezeigt (obwohl Items vorhanden sind, die nicht hervorgehoben sind).
3. Wenn ich Auswähle, dass nur NICHT Hervorgehobene angezeigt werden sollen, dann springt der Filter beim speichern auf - (also auf eine leere Auswahl).

## Describe the expected behaviour of the application

1. Ist das erwartete Verhalten
2. Hier sollten einfach alle Items ausgegeben werden, da ich ja nichts Auswähle bei dem Filter
3. Hier sollten nur die NICHT hervorgehobenen ausgegeben werden (wobei diese Variante nur ein Bonus für mich ist).

Im Grunde ist es das selbe Verhalten wie bei 'Veröffentlicht', bis auf den Part, dass ich bei der Listenausgabe diesen Parameter selber auswählen kann und nicht zwei Filtersets anlegen muss.

Viele Grüße

**Comment by zonky2** [comment]
@MacKP btw: Checkboxen in dem Github-Template so "checken" `- [x]`

**Comment by MacKP** [comment]
Der Fix von @discordier funktioniert für mich wunderbar. Ich kann alle drei Zustände abfragen und ausgeben:
1. Alle Items die einen Haken bei der Checkbox haben.
2. Alle Items werden ausgeben (keine Auswahl bei dem Filter)
3. Alle Items die keinen Haken bei der Checkbox haben werden ausgegeben.
Damit kann das Verhalten wie bei News etc. in Contao abgebildet werden. Wunderbar.

Vielen Dank ;-)

**Comment by zonky2** [comment]
@discordier würdest Du releasen?
